#cloud-config
users:
  - name: root
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6qU90rL3jmSCdGsCP/kMMkvaI3hhoI1vGGe0sLZ+gJYdL9srEEkDImmV5y+Rxwg46zfIMh6v3WTYv+Lf1e/AfSxd2q7WPZ/Vpk1wqzQydS8cA+ufNT11W45fj++uKLHuUx5dbkXGGgkLjXKVxvW1Z1g6eaIYP7KDS8UR+2nlx0DEiXjr30jBqfMqOs1NMz8ILmznQkoUGl4zztHVrlpwPTqiCi4fPKed/OZR/FmNgiIJ8HJSIN/ovqj/qzXKC6C+SPArmlVt5QoOU0vN+6dWgHpJ4vB+xaUZtY0HYl0dm+NsFe8kOgfQPHAuffDl0G95qj9LDl9mAcIBl1rzRQ9JpKHjxPorWhnSy6+mJ3AI4q9hCqLuN4OSCDM4YvdJPSdj33oOFP9oX2KxwJfo7NRbUioB/gANjbFwWFr1dKHozV6z2NvORPW5jnpCCAZQdNSqd62S7Gy4Gtdk4NJo3myEyUE9sxdShYW44UnTUhvvGXGlJ06P78v7jbuozpOjRZYGICPwsCYmdmVDTnzRvwrsbXfXmmIaaUyh+7OaGVqOnaaPqrCbCrm1lYzRpkzLpX2acBqmX/Mh9VpYW6poLFxz/sjVuiM21u/0BlcJHsnc71UKxctM2dyUM66duDRYBlhAPtg2GehitYEHzQ2r1wKQRCSHA/r8GZipBf58WA3Q9cw== lambda@lambdas-MacBook-Air.local
package_upgrade: true
packages:
      - ca-certificates
      - curl
      - gnupg
      - vim
      - git
      - zip
      - unzip
      - openssl
      - libssl-dev
      - build-essential
      - libclang-dev
runcmd:
  - apt-get install pkg-config cmake clang lldb lld -y
  - wget -P /root/ https://nodejs.org/dist/v18.18.0/node-v18.18.0-linux-x64.tar.xz
  - tar -xf /root/node-v18.18.0-linux-x64.tar.xz --directory=/usr/local/ --strip-components=1
  - rm /root/node-v18.18.0-linux-x64.tar.xz
  - npm install --global yarn
  - sudo apt install postgresql -y
  - sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
  - git clone https://github.com/matter-labs/block-explorer.git /root/block-explorer
  - cd /root/block-explorer && npm install && awk '{sub("BLOCKCHAIN_RPC_URL=http://localhost:3050", "BLOCKCHAIN_RPC_URL=http://10.0.1.3:3050")}1' packages/worker/.env.example > packages/worker/.env && awk '{sub("CONTRACT_VERIFICATION_API_URL=http://127.0.0.1:3070", "CONTRACT_VERIFICATION_API_URL=http://10.0.1.3:3070")}1' packages/api/.env.example > packages/api/.env && npm run db:create && npm run dev